name:       flashcards
version:    1.0.0
#license:    ...
maintainer: josh@fortytwo.net
#copyright:  ...

#extra-source-files:

library:
  source-dirs: src/main/haskell

dependencies:

- time
- random-shuffle
- directory
- split
- containers